# Generated by Django 4.2 on 2023-04-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_prev',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='main_app.client'), on_delete=django.db.models.deletion.PROTECT, to='main_app.client'),
        ),
    ]
