# Generated by Django 4.2 on 2023-07-01 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.EmailField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_comments',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='unit',
            name='bios_password',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='os_password',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='condition',
        ),
        migrations.CreateModel(
            name='UnitCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='condition',
            field=models.ManyToManyField(blank=True, null=True, related_name='units', to='main_app.unitcondition'),
        ),
    ]
