# Generated by Django 4.2 on 2023-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_image',
            field=models.CharField(default='No info', max_length=56),
        ),
    ]
