# Generated by Django 4.2 on 2023-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_unitcondition_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='condition',
            field=models.ManyToManyField(blank=True, null=True, related_name='units', to='main_app.unitcondition'),
        ),
    ]
