# Generated by Django 4.2 on 2023-04-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_diagnostic_result_order_required_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.client'),
        ),
    ]
