# Generated by Django 4.2 on 2023-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_unit_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='units', to='main_app.unitcondition'),
        ),
    ]
