# Generated by Django 4.2 on 2023-04-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_order_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cl',
        ),
    ]
