# Generated by Django 4.2 on 2023-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_client_mail_alter_unit_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='No address', max_length=42, null=True),
        ),
    ]
