# Generated by Django 4.2 on 2023-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_comments',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_image',
            field=models.CharField(default='No info', max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='defect',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='order',
            name='diagnostic_result',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='order',
            name='required_works',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_image',
            field=models.CharField(default='No info', max_length=70),
        ),
    ]
