# Generated by Django 4.2 on 2023-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_stage_order_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
